config/routes.rb
Profile::Application.routes.draw do
  get "micro_posts/refresh"
  get "micro_posts/destroy_all"
  match 'micro_posts/feed' => 'micro_posts#feed', :defaults => { :format =>'rss' }, 
      :as => :micro_posts_feed
  resources :micro_posts

  get "home/index"

  get "entries/new_blog", :as => :new_blog_entry
  get "entries/new_github", :as => :new_github_entry
  get "entries/new_auto", :as => :new_auto_entry
  match "/entries/retry/:id" => "entries#retry", :as => :retry_entry, :via => :get
  resources :entries

  devise_for :users
  resources :users, :only => [:index, :show]  do 
    member do
      get :following, :followers, :entry
      get :posts
      post :refresh_posts
      match "/refresh_progress/:job_id" => "users#refresh_progress", :as => :refresh_progress, :via => :post
    end
  end
  
  resources :relationships, :only => [:create, :destroy]

  get 'settings/profile'
  put 'settings/profile_p'
  get 'settings/password'
  put 'settings/password_p'

  match "/about" => "home#about", :as => :about, :via => :get
  match "/stat" => "home#stat", :as => :stat, :via => :get
  match "/intro" => "home#intro", :as => :intro, :via => :get
  match "/story" => "home#story", :as => :story, :via => :get
  match "/suggest" => "home#suggest", :as => :suggest, :via => :get
  match "/update_log" => "home#update_log", :as => :update_log, :via => :get

  root :to => 'home#intro'

end

app/models/entry.rb
 
class Entry < ActiveRecord::Base
  belongs_to :user
  require 'open-uri'

  def self.create(hash, user)
    entry = Entry.new(hash)
    entry.fix_url
    user.add_entry(entry)
    entry.user = user
    entry
  end

  def create_posts_from_rss(tag, jobs_id)
    ret = false
    rss = Feed.get_rss rss_url, jobs_id
    if rss.nil?
      return ret
    end
    if rss.class == RSS::Rss
      ret = true
      rss.items.each do |item|
        user.create_post_from_rss(item, tag) unless user.has_post?(item.link)
      end
    elsif rss.class == RSS::Atom::Feed
      ret = true
      rss.entries.each do |entry|
        user.create_post_from_atom(entry, tag) unless user.has_post?(entry.link.href)
      end
    else
      logger.warn "not support feed type #{rss.class}"
    end
    return ret
  end

  def wait_feed_cache(jobs_id)
    WaitFeedCache.add(rss_url, jobs_id)
  end

  def cached? 
    rss = Feed.has_cache? rss_url
    return true if rss
    false
  end

  def processing?
    ProcessJob.exist? rss_url
  end

  def try_complete
    self.completed = 0
    fix_url
    self.save!
    EntryRssJob.schedule url, id, user.id
  end

  def completed?
    completed == 1
  end

  def failed?
    completed == -1
  end

  def fix_url
    u = URI.parse(self.url)
    if u.scheme.nil?
      self.url = "http://" + self.url
      return true
    end
    false
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @entries = current_user.all_entries
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @entry = Entry.find(params[:id])
    data = {}
    data[:id] = @entry.id
    if @entry.completed?
      data[:entry] = render_to_string :partial => 'entries/entry'
      data[:complete] = "success"
    elsif @entry.failed?
      data[:complete] = "failed"
      data[:err_msg] = render_to_string :partial => "entries/status"
    else
      data[:complete] = "wait"
    end
    respond_to do |format|
      format.js { render :json => data.to_json, :content_type => 'application/json' }
    end
  end

  def retry
    @entry = Entry.find(params[:id])
    @entry.try_complete unless @entry.completed?
    redirect_to @entry.user
  end

  def new
    @entry = Entry.new
    @title = t "title.add_manual_entry"
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def new_blog
    @entry = Entry.new
    @title = t "title.add_blog_entry"
  end

  def new_github
    @entry = Entry.new
    @title = t "title.add_github_entry"
  end

  def new_auto
    @entry = Entry.new
    @title = t "title.add_auto_entry"
  end

  def edit
    @entry = Entry.find(params[:id])
    @title = t "title.edit_entry"
  end

  def create
    @entry = Entry.create(params[:entry], current_user)
    @entry.try_complete
    respond_to do |format|
      if @entry.save
        format.html { redirect_to user_path(current_user), notice: 'add done' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @entry = Entry.find(params[:id])
    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to edit_entry_path(@entry), notice: 'Entry was successfully updated.' }
      else
        flash.now[:alert] = "update entry failed"
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to current_user }
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_auto.html.erb
<div class="tips">
  <%= t "tip.auto_entry" %>
</div>
<%= form_for(@entry) do |f| %>
  <dl>
    <dt><%= f.label :url, t(:url) %></dt>
    <dd><%= f.text_field :url, :class => 'txt-ctrl', :size => "45" %></dd>
  </dl>
  <dl>
    <dd>
      <%= link_to_submit t(:add), :class => 'link-btn' %>
      <%= link_to t("entry.back"), user_path(current_user), :class => 'link-btn' %>
    </dd>
  </dl>
<% end %>

app/views/entries/_blog.html.erb
<div class="tips">
  <%= t "tip.blog_entry" %>
</div>
<%= form_for(@entry) do |f| %>
  <%= hidden_field_tag :method, :blog %>
  <dl>
    <dt><%= f.label :rss_url, t(:rss_url) %></dt>
    <dd><%= f.text_field :rss_url, :class => 'txt-ctrl', :size => "45" %></dd>
  </dl>
  <dl>
    <dd>
      <%= link_to_submit t(:add), :class => 'link-btn' %>
      <%= link_to t("entry.back"), user_path(current_user), :class => 'link-btn' %>
    </dd>
  </dl>
<% end %>

app/views/entries/_edit.html.erb
<%= form_for(@entry) do |f| %>
  <dl>
    <dt><%= f.label :title, t("entry.title") %></dt>
    <dd><%= f.text_field :title, :class => 'txt-ctrl', :size => 35 %></dd>
  </dl>
  <dl>
    <dt><%= f.label :url, t(:url) %></dt>
    <dd><%= f.text_field :url, :class => 'txt-ctrl', :size => 35 %></dd>
  </dl>
  <dl>
    <dt><%= f.label :rss_url, t(:rss_url) %></dt>
    <dd><%= f.text_field :rss_url, :class => 'txt-ctrl', :disabled => true, :size => 35 %></dd>
  </dl>
  <dl>
    <dt><%= f.label :description, t("entry.desc") %></dt>
    <dd><%= f.text_area :description, :size => "60x4", :class => 'txt-ctrl' %></dd>
  </dl>
  <dl>
    <dd>
      <%= link_to_submit t(:update), :class => 'link-btn' %>
      <%= link_to t("entry.delete"), @entry, :method => 'delete', :class => 'link-btn' %>
      <%= link_to t("entry.back"), user_path(@entry.user), :class => 'link-btn' %>
    </dd>
  </dl>
<% end %>

app/views/entries/_frame.html.erb
<%= render 'shared/avatar-header' %>
<div id="main" style="width: 100%">
<%= render 'entries/tab_nav', :current => current %>
<div id="setting">
  <%= render :partial => content %>
</div>
</div>

app/views/entries/_github.html.erb
<div class="tips">
  <%= t "tip.github_entry" %>
</div>
<%= form_for(@entry) do |f| %>
  <%= hidden_field_tag :method, :github %>
  <dl>
    <dt><%= f.label :url, t(:github_url) %></dt>
    <dd><%= f.text_field :url, :class => 'txt-ctrl', :size => "45" %></dd>
  </dl>
  <dl>
    <dd>
      <%= link_to_submit t(:add), :class => 'link-btn' %>
      <%= link_to t("entry.back"), user_path(current_user), :class => 'link-btn' %>
    </dd>
  </dl>
<% end %>

app/views/entries/_quickadd.html.erb
<div id="quickadd" style="display:none;">
<%= form_for(:entry, :url => entries_path) do |f| %>
  <div><p><%= t "tip.general" %></p></div>
  <div id="error_tip"></div>
  <div><%= f.text_field :url, :class => 'txt-ctrl', :size => "35", :id => 'url_text' %></div>
  <div id="buttons">
    <%= link_to t(:add), '#', :class => 'link-btn-small', :onclick => "check_submit(); return false" %>
    <%= link_to t("entry.back"), '#', :onclick => "hide_quickadd(); return false;",
            :class => 'link-btn-small' %>
    <%= link_to t("entry.more"), new_auto_entry_path, :class => 'link-btn-small' %>
  </div>
<% end %>
</div>

app/views/entries/_status.html.erb
<% entry ||= @entry %>
<% if entry.failed? %>
  <%= entry.description %>
  <b><%= link_to 'retry', retry_entry_path(entry), :style => "color: #4183c4;" %></b>
<% else %>
  <%= entry.url %>
  <script type="text/javascript">
    start_refresh_entry('<%= entry_path(entry) %>')
  </script>
<% end %>

app/views/entries/_tab_nav.html.erb
<div class="tab-nav-frame">
  <ul class="tab-nav">
    <li><%= link_to t("entry.add_auto"), new_auto_entry_path, is_current?(:auto, current) %></li>
    <li><%= link_to t("entry.manual_add"), new_entry_path, is_current?(:manual, current) %></li>
  </ul>
</div>

app/views/entries/edit.html.erb
<%= render 'shared/avatar-header' %>
<div id="main" style="width: 100%">
<h3 class="window-title"><%= t "entry.edit" %> </h3>
<div id="setting">
  <div class="op-tip">
    <%= content_tag :div, flash[:alert], :class => "alert" if flash[:alert] %>
    <%= content_tag :div, flash[:notice], :class => "notice" if flash[:notice] %>
  </div>
  <%= render "entries/edit" %>
</div>
</div>

app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Tag</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entries.each do |entry| %>
  <tr>
    <td><%= entry.url %></td>
    <td><%= entry.tag %></td>
    <td><%= link_to 'Show', entry %></td>
    <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
    <td><%= link_to 'Destroy', entry, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<%= render 'entries/frame', :content => 'entries/manual_add', :current => :manual %>

app/views/entries/new_auto.html.erb
<%= render 'entries/frame', :content => 'entries/auto', :current => :auto %>

app/views/entries/new_blog.html.erb
<%= render 'entries/frame', :content => 'entries/blog', :current => :blog %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @entry.url %>
</p>

<p>
  <b>Tag:</b>
  <%= @entry.tag %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>