config/routes.rb
Profile::Application.routes.draw do
  get "micro_posts/refresh"
  get "micro_posts/destroy_all"
  match 'micro_posts/feed' => 'micro_posts#feed', :defaults => { :format =>'rss' }, 
      :as => :micro_posts_feed
  resources :micro_posts

  get "home/index"

  get "entries/new_blog", :as => :new_blog_entry
  get "entries/new_github", :as => :new_github_entry
  get "entries/new_auto", :as => :new_auto_entry
  match "/entries/retry/:id" => "entries#retry", :as => :retry_entry, :via => :get
  resources :entries

  devise_for :users
  resources :users, :only => [:index, :show]  do 
    member do
      get :following, :followers, :entry
      get :posts
      post :refresh_posts
      match "/refresh_progress/:job_id" => "users#refresh_progress", :as => :refresh_progress, :via => :post
    end
  end
  
  resources :relationships, :only => [:create, :destroy]

  get 'settings/profile'
  put 'settings/profile_p'
  get 'settings/password'
  put 'settings/password_p'

  match "/about" => "home#about", :as => :about, :via => :get
  match "/stat" => "home#stat", :as => :stat, :via => :get
  match "/intro" => "home#intro", :as => :intro, :via => :get
  match "/story" => "home#story", :as => :story, :via => :get
  match "/suggest" => "home#suggest", :as => :suggest, :via => :get
  match "/update_log" => "home#update_log", :as => :update_log, :via => :get

  root :to => 'home#intro'

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me,
    :description
  validates :name, :presence => true, :uniqueness => true
  has_many :entrys, :dependent => :destroy
  has_many :micro_posts, :dependent => :destroy
  has_many :relationships, :foreign_key => "follower_id", :dependent => :destroy
  has_many :following, :through => :relationships, :source => :followed
  has_many :reverse_relationships, :foreign_key => "followed_id", 
      :class_name => 'Relationship', :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower

  def add_entry(entry)
    self.entrys << entry
    reset_posts_update_time
  end

  def all_entries
    entrys
  end

  def add_post(post)
    self.micro_posts << post
    logger.info "add post #{post.title} to #{name}"
  end

  def has_post?(url)
    micro_posts.each do |post|
      return true if url.downcase == post.url
    end
    return false
  end

  def refresh_self_and_following_posts(jobs_id)
    create_post_from_entries jobs_id
    following.each do |user|
      user.create_post_from_entries jobs_id
    end
  end

  def create_post_from_entries(jobs_id)
    return unless need_update_posts?
    ret = false
    entrys.each do |entry|
      if entry.completed?
        if entry.processing?
          entry.wait_feed_cache jobs_id
        else
          ret = entry.create_posts_from_rss entry.tag, jobs_id
        end
      end
    end
    set_posts_update_time if ret
  end

  def job_count_self
    return 0 unless need_update_posts?
    sum = 0
    entrys.each do |entry|
      if entry.completed?
        sum += 1 unless entry.cached?
      end
    end
    sum
  end

  def job_count_self_and_following
    sum = job_count_self
    following.each do |user|
      sum += user.job_count_self
    end
    sum
  end

  # return the job-list id
  def add_job_progress(sum)
    return JobProgress.add(sum) if sum > 0
    -1
  end

  def create_post_from_rss(item, tag)
    # item.pubDate.to_s fix an issue: http://stackoverflow.com/questions/9155190/insert-to-database-error-on-heroku-but-worked-locally-activerecordstatementin
    post = MicroPost.new(:description => item.description, :url => item.link, 
                         :title => item.title, :pub_date => item.pubDate.to_s,
                         :tag => tag)
    add_post(post)
    post.user = self
  end

  def create_post_from_atom(item, tag)
    post = MicroPost.new(:description => item.content.content || "No description",
                         :url => item.link.href || "No url", 
                         :title => item.title.content || "No title",
                         :pub_date => item.published.content.localtime.to_s,
                         :tag => tag)
    post.user = self
    add_post(post)
  end

  def following?(followed)
    relationships.find_by_followed_id(followed)
  end

  def follow!(followed)
    relationships.create!(:followed_id => followed.id) unless following? followed
  end

  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy if following? followed
  end

  def feed
    MicroPost.from_users_followed_by(self)
  end

  def need_update_posts?
    return true if posts_update_at.nil?
    Time.now.utc - posts_update_at > 2 * 60
  end

  def set_posts_update_time
    self.posts_update_at = Time.now.utc
    save!
  end

  def reset_posts_update_time
    self.posts_update_at = Time.utc(1986)
    save!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  respond_to :html, :js, :json

  def show
    @user = User.find(params[:id])
    @title = @user.name
    load_posts @user
  end

  def followers
    @user = User.find(params[:id])
    @title = t "title.follower"
  end

  def following
    @user = User.find(params[:id])
    @title = t "title.following"
  end

  def posts
    @user = User.find(params[:id])
    load_posts @user
    respond_to do |format|
      format.js
    end
  end

  def refresh_posts
    @user = User.find(params[:id])
    job_sum = 0
    @job_id = -1
    if is_current_user? @user
      job_sum = @user.job_count_self_and_following
      @job_id = @user.add_job_progress job_sum
      @user.refresh_self_and_following_posts @job_id
    else
      job_sum = @user.job_count_self
      @job_id = @user.add_job_progress job_sum
      @user.create_post_from_entries @job_id
    end
    load_posts @user
    respond_to do |format|
      format.js
    end
  end

  # get the refresh_posts progress
  def refresh_progress
    @user = User.find(params[:id])
    @job_id = params[:job_id].to_i
    if @job_id < 0
      redirect_to user_path(@user)
    end
    if JobProgress.all_done? @job_id
      @job_id = -1
      generate_posts @user
      load_posts @user
    end
    data = { :progress => @job_id }
    if @job_id < 0
      data[:posts] = render_to_string :partial => 'shared/posts'
      data[:update_at] = render_to_string :partial => 'users/posts_update_time'
    end
    respond_to do |format|
      format.js { render :json => data.to_json, :content_type => 'application/json' }
    end
  end

  def entry
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  private
    def is_current_user?(user)
      return current_user == user if user_signed_in?
      false
    end

    def load_posts(user)
      if is_current_user? user
        focus_user = params[:user].to_i > 0 ? User.find(params[:user].to_i) : nil
        if focus_user
          @micro_posts = focus_user.micro_posts.paginate(:page => params[:page], :per_page => 5)
        else
          @micro_posts = user.feed.paginate(:page => params[:page], :per_page => 5)
        end
      else
        @micro_posts = user.micro_posts.paginate(:page => params[:page], :per_page => 5)
      end
    end

    def generate_posts(user)
      if is_current_user? user
        user.refresh_self_and_following_posts -1
      else
        user.create_post_from_entries -1
      end
    end
end

app/helpers/user_helper.rb
module UserHelper
  def user_description(user)
    if user.description.nil? or user.description.empty? 
      t :no_description
    else
      user.description
    end
  end

  def user_entry_count(user)
    return user.entrys.count if user == current_user 
    cnt = 0
    user.entrys.each do |entry|
      cnt += 1 if entry.completed?
    end
    cnt
  end

  def user_follower_desc(user)
    if user == current_user 
      t :self_follower
    else
      t :other_follower
    end
  end

  def user_following_desc(user)
    if user == current_user 
      t :self_following
    else
      t :other_following
    end
  end
end

app/views/users/_activity_link.html.erb
<% if @user == current_user %>
<div id="activity-link" class="popup round" style="display:none">
  <%= link_to t(:showall), posts_user_path(@user), :remote => true %>
  <%= link_to t(:showself), posts_user_path(current_user, :user => current_user), :remote => true %>
</div>
<script type="text/javascript">
  $(document).ready(function() {
      $('#activity-title').mouseover(function() { show_popup('#activity-link', '#activity-title'); })
   });
</script>
<% end %>

app/views/users/_follow.html.erb
<%= form_for current_user.relationships.build :followed_id => user.id do |f| %>
  <%= f.hidden_field :followed_id %>
  <%= f.submit t(:follow), :class => "link-btn-small" %>
<% end %>

app/views/users/_posts_update_time.html.erb
<% if not @user.posts_update_at.nil? and @user.posts_update_at > Time.utc(1986) %>
  (<%= t :updated_before, :desc => distance_of_time_in_words(@user.posts_update_at, Time.now.utc) %>)
<% end %>

app/views/users/_showhim.html.erb
<span class="popup" style="display:none; background: white;">
  <%= t :showhim %>
</span>

app/views/users/_unfollow.html.erb
<%= form_for current_user.relationships.find_by_followed_id(user), :html => 
    {:method => :delete} do |f| %>
  <%= f.submit t(:unfollow), :class => 'link-btn-small' %>
<% end %>

app/views/users/entry.html.erb
<%= render 'shared/avatar-header', :user => @user %>
<div id="main">
  <%= pluralize(@user.entrys.count, "entry") %>
  <% @user.entrys.each do |entry| %>
    <h3><%= entry.url %></h3>
  <% end %>
  <%= link_to 'Add new', new_entry_path if current_user == @user %>
</div>

app/views/users/followers.html.erb
<% @title = user_follower_desc @user %>
<%= render 'shared/avatar-header', :user => @user %>
<div id="main">
  <h2><%= t :follower_msg, :name => @user.name, :count => @user.followers.count %></h2>
  <%= render 'shared/users', :users => @user.followers %>
</div>

app/views/users/following.html.erb
<% @title = user_following_desc @user %>
<%= render 'shared/avatar-header', :user => @user %>
<div id="main">
  <h2><%= t :following_msg, :name => @user.name, :count => @user.following.count %></h2>
  <%= render 'shared/users', :users => @user.following %>
</div>

app/views/users/index.html.erb
<%= render 'shared/avatar-header' %>
<div id="main">
  <h2><%= t :random_user %></h2>
  <%= render 'shared/users', :users => @users %>
</div>

app/views/users/posts.js.erb
$('#post-list').html("<%= escape_javascript(render('shared/posts')) %>")

app/views/users/refresh_posts.js.erb
<% if @job_id < 0 %>
  enable_refresh_link();
  $('#post-list').html("<%= escape_javascript(render('shared/posts')) %>")
  $('#posts-update-time').html("<%= escape_javascript(render('users/posts_update_time')) %>")
<% else %>
  var url = '<%= refresh_progress_user_path(@user, :job_id => @job_id, :page => params[:page], 
          :user => params[:user]) %>'
  start_refresh_progress(url);
<% end %>

app/views/users/show.html.erb
<%= render 'shared/avatar-header', :user => @user %>
<%= render 'shared/header-profile', :user => @user %>
<div id="all-entries">
  <h3 class="window-title">
    <%= t "entry.brief" %> (<%= @user.entrys.count %>)
    <% if @user == current_user %>
      <%= link_to t(:new_entry), '#', :class => "title-link", :id => "add-entry-link",
            :onclick => "switch_quickadd('#add-entry-link'); return false;" %>
      <%= render 'entries/quickadd' %>
    <% end %>
  </h3>
  <% if user_entry_count(@user).zero? %>
    <div class="notice gray">
      <% if @user == current_user %>
        <div class="no_entry_tip">
          <p><%= t "tip.no_entry" %></p>
          <%= link_to t("entry.add_now"), "#", :class => 'link-btn', :id => "add_now_link",
                :onclick => "switch_quickadd('#add_now_link'); return false;" %>
        </div>
      <% else %>
          <%= t "tip.other_no_entry" %>
      <% end %>
    </div>
  <% else %>
    <div id="entry-list">
      <%= render @user.entrys %>
    </div>
  <% end %>
</div>
<div id="all-posts">
  <h3 class="window-title">
    <%= link_to t(:activity), posts_user_path(@user), :id => 'activity-title', :remote => true %>
    <%= link_to t(:refresh_post), refresh_posts_user_path(@user, :page => params[:page], :user => params[:user]), 
                :id => 'refresh-link', :remote => true, :class => "title-link", :method => :post %>
    <span id="posts-update-time" class="quiet"><%= render 'users/posts_update_time' %></span>
  </h3>
  <%= render 'users/activity_link' %>
  <%= render 'shared/posts' %>
</div> 