config/routes.rb
Profile::Application.routes.draw do
  get "micro_posts/refresh"
  get "micro_posts/destroy_all"
  match 'micro_posts/feed' => 'micro_posts#feed', :defaults => { :format =>'rss' }, 
      :as => :micro_posts_feed
  resources :micro_posts

  get "home/index"

  get "entries/new_blog", :as => :new_blog_entry
  get "entries/new_github", :as => :new_github_entry
  get "entries/new_auto", :as => :new_auto_entry
  match "/entries/retry/:id" => "entries#retry", :as => :retry_entry, :via => :get
  resources :entries

  devise_for :users
  resources :users, :only => [:index, :show]  do 
    member do
      get :following, :followers, :entry
      get :posts
      post :refresh_posts
      match "/refresh_progress/:job_id" => "users#refresh_progress", :as => :refresh_progress, :via => :post
    end
  end
  
  resources :relationships, :only => [:create, :destroy]

  get 'settings/profile'
  put 'settings/profile_p'
  get 'settings/password'
  put 'settings/password_p'

  match "/about" => "home#about", :as => :about, :via => :get
  match "/stat" => "home#stat", :as => :stat, :via => :get
  match "/intro" => "home#intro", :as => :intro, :via => :get
  match "/story" => "home#story", :as => :story, :via => :get
  match "/suggest" => "home#suggest", :as => :suggest, :via => :get
  match "/update_log" => "home#update_log", :as => :update_log, :via => :get

  root :to => 'home#intro'

end

app/views/shared/_51la.html.erb
<script language="javascript" type="text/javascript" src="http://js.users.51.la/6933048.js"></script>
<noscript><a href="http://www.51.la/?6933048" target="_blank"><img alt="&#x6211;&#x8981;&#x5566;&#x514D;&#x8D39;&#x7EDF;&#x8BA1;" src="http://img.users.51.la/6933048.asp" style="border:none" /></a></noscript>

app/views/shared/_avatar-header.html.erb
  <% user ||= current_user %>
  <table class="profile">
    <tr>
      <td class="user">
        <ul>
          <li><h1><%= gravatar_for user, :size => 48 %> <%= user.name %></h1></li>
          <li class="v-center"><%= render 'shared/follow_btn', :user => user %></li>
        </ul>
      </td>
      <td class="follow-stats">
        <ul>
          <li>
            <a href="<%= followers_user_path user %>">
              <strong><%= user.followers.count %></strong>
              <span><%= user_follower_desc user %></span>
            </a>
          </li>
          <li>
            <a href="<%= following_user_path user %>">
              <strong><%= user.following.count %></strong>
              <span><%= user_following_desc user %></span>
            </a>
          </li>
        </ul>
      </td>
    </tr>
  </table>

app/views/shared/_dashboard.html.erb
<div id="dashboard">
  <ul class="nav">
  <% if user_signed_in? %>
    <li><%= gravatar_for(current_user, :size => 30) %>
    <li class="name"><%= link_to current_user.name, user_path(current_user) %>
    <li><%= link_to t(:user_index), user_path(current_user) %>
    <li><%= link_to t(:edit_profile), settings_profile_path %>
    <li><%= link_to t(:look_around), users_path %>
    <li><%= link_to t(:sign_out), destroy_user_session_path, :method => :delete %>
  <% else %>
    <li><%= link_to t(:sign_up), new_registration_path(resource_name) %>
    <li><%= link_to t(:sign_in), new_session_path(resource_name) %>
  <% end %>
  <li><%= link_to t(:update_log), update_log_path, :class => "highlight" %>
  <li><%= link_to t(:all_activity), micro_posts_path %>
  <% if Rails.env == "development_" %>
    <li><%= link_to 'All users', users_path %>
    <li><%= link_to 'Destroy all posts', micro_posts_destroy_all_path %>
  <% end %>
  </ul>
</div>

app/views/shared/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = 'codertrace'; 
    var disqus_url = '<%= disqus_url %>';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/shared/_follow_btn.html.erb
<% if current_user != user %>
  <% if current_user.following? user %>
    <%= render 'unfollow', :user => user %>
  <% else %>
    <%= render 'follow', :user => user %>
  <% end %>
<% end %>

app/views/shared/_header-profile.html.erb
<div id="user-profile">
  <div class="base">
  <dl>
    <dt><%= t :name %></dt>
    <dd><%= user.name %></dd>
  </dl>
  <dl>
    <dt><%= t :index_url %></dt>
    <dd><%= link_to user_url(user), user_path(user) %></dd>
  </dl>
  <dl>
    <dt><%= t :email %></dt>
    <dd><%= user.email %></dd>
  </dl>
  <dl>
    <dt><%= t :description %></dt>
    <dd><%= user_description user %></dd>
  </dl>
  </div>
</div>

app/views/shared/_posts.html.erb
<div id="post-list">
<% if @micro_posts.count.zero? %>
  <div class="notice gray">
    <% if @user == current_user %>
      <%= t "tip.no_activity" %>
    <% else %>
      <%= t "tip.other_no_activity" %>
    <% end %>
  </div>
<% else %>
  <%= render @micro_posts %>
  <div class="flickr_pagination">
    <%= will_paginate @micro_posts, :inner_window => 1, 
        :params => {:controller => 'users', :action => 'show', :id => @user.id, :user => params[:user] } %>
  </div>
<% end %>
</div>

app/views/shared/_sidebar.html.erb
<div id="sidebar">
  <div id="profile">
    <% user ||= current_user %>
    <%= gravatar_for user %>&nbsp;
    <h3><%= link_to user.name, user_path(user) %></h3>
    <%= render 'shared/stats', :user => user %>
  </div>
</div>

app/views/shared/_signin.html.erb
<div class="login_form">
<h2 class="window-title"><%= t :sign_in %></h2>
<div class="formbody">
<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <%= content_tag :div, flash[:alert], :class => "alert" if flash[:alert] %>
  <div>
    <%= f.label :email, t(:email) %><br />
    <%= f.email_field :email, :class => 'txt-ctrl' %>
  </div>
  <div>
    <%= f.label :password, t(:password) %><br/>
    <%= f.password_field :password, :class => 'txt-ctrl' %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div><%= f.check_box :remember_me %> <%= f.label :remember_me, t(:remember_me) %></div>
  <% end -%>

  <div>
    <%= f.submit t(:sign_in), :class => 'link-btn' %>
    <%= link_to t(:forgot_your_password), new_password_path(resource_name), 
        :class => "quiet", :style => "float: right" %>
  </div>
<% end %>
</div>
</div>

app/views/shared/_stats.html.erb
<% user ||= current_user %>
<div class="stats">
  <ul class="stats-nav">
    <li><strong>URL: </strong><%= link_to user_url(user), user_path(user) %>
    <li><strong>Email: </strong><%= user.email %>
    <li><strong><%= pluralize(user.entrys.count, "entry") %></strong>
  </ul>
</div>

app/views/shared/_users.html.erb
<div class="users">
  <% users.each do |user| %>
  <div class="user">
    <div class="avatar">
      <%= gravatar_for user, :size => 48 %>
    </div>
    <div class="intro">
      <div class="meta">
        <span class="name"><%= link_to user.name, user_path(user) %></span>
        <div class="util">
          <%= render 'shared/follow_btn', :user => user %>
        </div>
      </div>
      <p class="description"><%= user_description user %></p>
    </div>
  </div>
  <% end %>
</div>