config/routes.rb
Profile::Application.routes.draw do
  get "micro_posts/refresh"
  get "micro_posts/destroy_all"
  match 'micro_posts/feed' => 'micro_posts#feed', :defaults => { :format =>'rss' }, 
      :as => :micro_posts_feed
  resources :micro_posts

  get "home/index"

  get "entries/new_blog", :as => :new_blog_entry
  get "entries/new_github", :as => :new_github_entry
  get "entries/new_auto", :as => :new_auto_entry
  match "/entries/retry/:id" => "entries#retry", :as => :retry_entry, :via => :get
  resources :entries

  devise_for :users
  resources :users, :only => [:index, :show]  do 
    member do
      get :following, :followers, :entry
      get :posts
      post :refresh_posts
      match "/refresh_progress/:job_id" => "users#refresh_progress", :as => :refresh_progress, :via => :post
    end
  end
  
  resources :relationships, :only => [:create, :destroy]

  get 'settings/profile'
  put 'settings/profile_p'
  get 'settings/password'
  put 'settings/password_p'

  match "/about" => "home#about", :as => :about, :via => :get
  match "/stat" => "home#stat", :as => :stat, :via => :get
  match "/intro" => "home#intro", :as => :intro, :via => :get
  match "/story" => "home#story", :as => :story, :via => :get
  match "/suggest" => "home#suggest", :as => :suggest, :via => :get
  match "/update_log" => "home#update_log", :as => :update_log, :via => :get

  root :to => 'home#intro'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title = t "title.home"
    if user_signed_in? 
      redirect_to user_path(current_user)
    else
      @posts = MicroPost.paginate(:page => params[:page], :per_page => 5)
    end
  end

  def about
    @title = t "title.about"
  end

  def intro
    @full_title = t "title.site"
    if user_signed_in? 
      redirect_to user_path(current_user)
    end
  end

  def story
    @title = t "title.about"
  end

  def update_log
    @title = t "title.update_log"
  end

  def suggest
    @title = t "title.suggest"
  end

  def stat
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def history_content
    content = ""
    File.open('public/history.txt', 'r') do |file|
        content = file.sysread(file.size)
        Common.force_utf8! content
        content = Maruku.new(content).to_html
    end
    content
  end
end

app/views/home/_tab_nav.html.erb
<div class="tab-nav-frame">
<ul class="tab-nav">
  <li><%= link_to t(:about), about_path, is_current?(:about, current) %></li>
  <li><%= link_to t(:story), story_path, is_current?(:story, current) %></li>
  <li><%= link_to t(:update_log), update_log_path, is_current?(:update_log, current) %></li>
</ul>
</div>

app/views/home/about.html.erb
<%= render 'home/tab_nav', :current => :about %>
<div id="about-content">
  <p><%= t "site.intro" %></p>
  <p>
    <%= t "site.add_entry" %><br/>
    <%= image_tag 'about/add-entry.png' %>
  </p>
  <p>
    <%= t "site.main_page" %><br/>
    <%= image_tag 'about/activity.png' %>
  </p>
  <p>
    <%= t "site.enjoy_it" %><%= link_to t("site.title.story"), story_path %>
  </p>
</div>

app/views/home/index.html.erb
<div id="news-area">
    <h2 class="window-title"><%= t :latest_activity %></h2>
  <div id="post-list">
    <%= render @posts %>
  </div>
</div>
<div class="signin">
  <%= render 'shared/signin' %>
</div>

app/views/home/intro.html.erb
<div id='intro' class='round'>
  <div id='logo'>
    <strong class="big">Coder Trace</strong><br/>
    <strong class="medium"><%= t "site.logo_text" %></strong>
  </div>
  <div id='desc'>
    <%= t "site.intro" %>
    <%= link_to t("site.more_about"), about_path %>
  </div>
  <div id='signup'>
    <%= link_to t("site.signup_to_enjoy"), new_registration_path(resource_name), :class => 'big-button' %>
  </div>
  <div class='hor-signin'>
    <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
      <ul>
        <li>
          <%= f.label :email, t(:email) %>
          <%= f.email_field :email, :class => 'txt-ctrl', :size => 25 %>
        </li>
        <li>
          <%= f.label :password, t(:password) %>
          <%= f.password_field :password, :class => 'txt-ctrl', :size => 25 %>
        </li>
        <li class='last'>
          <label for>&nbsp;</label>
          <%= f.submit t(:sign_in), :class => 'link-btn-dark' %>
        </li>
        <li>
          <%= f.check_box :remember_me %> <%= f.label :remember_me, t(:remember_me) %>
        </li>
        <li>
          <%= link_to t(:forgot_your_password), new_password_path(resource_name), :class => "quiet" %>
        </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/home/stat.html.erb
<h3>User count: <%= User.all.count %>, Entry count: <%= Entry.all.count %></h3>
<h3>Sign in count info</h3>
<ul>
  <% User.order("sign_in_count desc").where("sign_in_count > 1").each do |user| %>
  <li>
    <%= link_to user.name, user_path(user) %>, 
    sign_in_count: <%= user.sign_in_count %>, 
    entry count: <%= user.entrys.count %>
  </li>
<% end %>
</ul>

app/views/home/story.html.erb
<%= render 'home/tab_nav', :current => :story %>
<div id="about-content">
  <p><%= t "site.story" %></p>
</div>

app/views/home/suggest.html.erb
<div id="about-content">
  <p><%= t "site.suggest" %></p>
</div>
<%= render 'shared/disqus', :disqus_url => "http://codertrace.com/suggest" %>

app/views/home/update_log.html.erb
<%= render 'home/tab_nav', :current => :update_log %>
<div id="history">
  <p>
    <%= sanitize history_content %>
  </p>
</div>
<%= render 'shared/disqus', :disqus_url => "http://codertrace.com/update_log" %>